---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: chord-bootstrap
spec:
  selector:
    matchLabels:
        app: chord-bootstrap
  template:
    metadata:
      labels:
        app: chord-bootstrap
    spec:
      containers:
      - name: chord
        image: chord:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5555
        - containerPort: 5556
        command: ["python3"]
        args: ["/opt/chord/node.py",
               "create", "1",
               "--internal-port", "5555",
               "--external-port","5556"
        ]
...